require './lib/synth.rb'

bpm = 140
drum_synth  = Instrument.new(bpm, NoiseOscillator.new(44100, 123.0, 0.6), [], nil, nil)
bass_synth  = Instrument.new(bpm, SawtoothOscillator.new(44100, 123.0, 0.3), [1.0], nil, nil)
voice_synth = Instrument.new(bpm, SineOscillator.new(44100, 220.0, 1.0), [0.1, 0.4], nil, nil)

drums = Track.new(drum_synth)
24.times do
  drums.notes << Note.new(:_, 0, 4)
  drums.notes << Note.new(:a, 0, 16)
  drums.notes << Note.new(:_, 0, 16)
  drums.notes << Note.new(:_, 0, 8)
end

bass = Track.new(bass_synth)
6.times do
  bass.notes << Note.new(:a, 0, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 1, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 2, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 2, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:c, 1, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:c, 2, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 1, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 2, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:f, 0, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:f, 0, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:f, 1, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 2, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:e, 0, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:e, 0, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:e, 1, 16)
  bass.notes << Note.new(:_, 1, 16)
  bass.notes << Note.new(:a, 2, 16)
  bass.notes << Note.new(:_, 1, 16)
end

voice = Track.new(voice_synth)

4.times do
  voice.notes << Note.new(:_, 1, 1)
end
voice.notes << Note.new(:_, 1, 4)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:_, 4, 16)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:_, 4, 16)
voice.notes << Note.new(:a, 4, 4)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:_, 4, 16)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:b, 4, 2)

voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:a, 4, 8)
voice.notes << Note.new(:c, 4, 4)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:a, 4, 16)
voice.notes << Note.new(:a, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:a, 4, 16)
voice.notes << Note.new(:a, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:d, 4, 4)
voice.notes << Note.new(:d, 4, 16)
voice.notes << Note.new(:_, 4, 16)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:b, 4, 8)
voice.notes << Note.new(:_, 4, 8)
voice.notes << Note.new(:a, 4, 8)

voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:a, 4, 8)
voice.notes << Note.new(:c, 4, 4)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:a, 4, 16)
voice.notes << Note.new(:a, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:a, 4, 16)
voice.notes << Note.new(:a, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:b, 4, 4)
voice.notes << Note.new(:_, 4, 4)

voice.notes << Note.new(:c, 4, 4)
voice.notes << Note.new(:a, 4, 8)
voice.notes << Note.new(:c, 4, 4)
voice.notes << Note.new(:a, 4, 4)
voice.notes << Note.new(:a, 4, 8)
voice.notes << Note.new(:c, 4, 16)
voice.notes << Note.new(:c, 4, 32)
voice.notes << Note.new(:_, 4, 32)
voice.notes << Note.new(:c, 4, 8)
voice.notes << Note.new(:d, 4, 8)
voice.notes << Note.new(:c, 4, 4)
voice.notes << Note.new(:b, 4, 4)


s = Song.new()
s.tracks = [drums, bass, voice]

wave = WaveFile.new(1, 44100, 8)
wave.sample_data = s.next_samples(s.sample_length)
wave.save $0[0..-3] + 'wav'
